// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOeWgT8AEY3cCjYwMAr_W-SVwodUZjVu8',
    appId: '1:324175187788:web:47481091256962e58bc9e9',
    messagingSenderId: '324175187788',
    projectId: 'remed-pab-5b6ae',
    authDomain: 'remed-pab-5b6ae.firebaseapp.com',
    storageBucket: 'remed-pab-5b6ae.firebasestorage.app',
    measurementId: 'G-QJ5E4EPZ7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkqS9ojKr4XeIYpXTgw5g8VfJhSM6nusQ',
    appId: '1:324175187788:android:00b2e39fe91074138bc9e9',
    messagingSenderId: '324175187788',
    projectId: 'remed-pab-5b6ae',
    storageBucket: 'remed-pab-5b6ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkAYpe92XAAhaZykJzoTxzrMakH_DJeAs',
    appId: '1:324175187788:ios:c5fd92858a631af58bc9e9',
    messagingSenderId: '324175187788',
    projectId: 'remed-pab-5b6ae',
    storageBucket: 'remed-pab-5b6ae.firebasestorage.app',
    iosBundleId: 'com.example.tugasremidi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkAYpe92XAAhaZykJzoTxzrMakH_DJeAs',
    appId: '1:324175187788:ios:c5fd92858a631af58bc9e9',
    messagingSenderId: '324175187788',
    projectId: 'remed-pab-5b6ae',
    storageBucket: 'remed-pab-5b6ae.firebasestorage.app',
    iosBundleId: 'com.example.tugasremidi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOeWgT8AEY3cCjYwMAr_W-SVwodUZjVu8',
    appId: '1:324175187788:web:5f933eb994c5a21c8bc9e9',
    messagingSenderId: '324175187788',
    projectId: 'remed-pab-5b6ae',
    authDomain: 'remed-pab-5b6ae.firebaseapp.com',
    storageBucket: 'remed-pab-5b6ae.firebasestorage.app',
    measurementId: 'G-SZJ8N5NTN2',
  );
}
